
from __future__ import annotations

import asyncio
import json
import sys
import uuid
import re
from contextlib import asynccontextmanager
from typing import AsyncIterator, Optional

from fastapi import FastAPI, HTTPException, Request, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from pydantic import BaseModel

from agents.compare_agent import build_compare_agent
from agents.faq_agent import build_faq_agent
from agents.web_agent import build_web_agent
from logger import _tool_event_queue
from agents.mathy import build_mathy
from agents.researcher import build_researcher
from agents.writer import build_writer
from config import config
from graph import build_direct, build_graph, build_supervisor
from logger import reset_steps, turn_summary

# ─── LangSmith tracing ────────────────────────────────────────────────────────
if config.langsmith.enabled and config.langsmith.api_key:
    import os
    os.environ.setdefault("LANGSMITH_TRACING",  "true")
    os.environ.setdefault("LANGSMITH_API_KEY",   config.langsmith.api_key)
    os.environ.setdefault("LANGSMITH_PROJECT",   config.langsmith.project)
    os.environ.setdefault("LANGSMITH_ENDPOINT",  config.langsmith.endpoint)
    print(f"[langsmith] Tracing activo → projecto '{config.langsmith.project}'")
else:
    print("[langsmith] Tracing desactivado (LANGSMITH_TRACING=false ou sem API key)")

# Estado global compartilhado entre requests
runtime: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    print(f"[server] Carregando modelo Ollama: {config.ollama.model}")
    print("[server] Subindo MCP server via stdio...")

    client = MultiServerMCPClient(
        {
            "switchboard": {
                "command": sys.executable,
                "args": ["-m", "mcp_server.server"],
                "transport": "stdio",
                "cwd": str(config.project_root),
            }
        }
    )
    tools = await client.get_tools()
    print(f"[server] Tools carregadas do MCP: {[t.name for t in tools]}")

    researcher = build_researcher(tools, config.ollama.researcher_model)
    writer = build_writer(tools, config.ollama.writer_model)
    mathy = build_mathy(tools, config.ollama.mathy_model)
    faq = build_faq_agent(tools)
    compare = build_compare_agent(tools)
    web = build_web_agent(tools)
    supervisor = build_supervisor(config.ollama.supervisor_model)
    direct = build_direct(config.ollama.direct_model)

    async with AsyncSqliteSaver.from_conn_string(config.memory_db) as checkpointer:
        graph = build_graph(researcher, writer, mathy, supervisor, direct, faq, compare, web, checkpointer)
        runtime["graph"] = graph
        runtime["mcp"] = client
        print("[server] Pronto. Agentes: faq · compare · web · researcher · writer · mathy · direct")
        print("[server] Endpoints: /chat /chat/stream /chat/resume /upload /health")
        try:
            yield
        finally:
            runtime.clear()
            print("[server] Encerrando...")


app = FastAPI(title="Agentrix Switchboard", lifespan=lifespan)

# CORS aberto para facilitar dev local (Expo Web / device fisico).
# Em producao, restrinja a allow_origins.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatMessage(BaseModel):
    role: str
    content: str


class Attachment(BaseModel):
    id: str
    name: str
    uri: Optional[str] = None
    mimeType: Optional[str] = None
    size: Optional[int] = None
    base64: Optional[str] = None


class ChatBody(BaseModel):
    conversationId: str
    userId: Optional[str] = None        # stable cross-conversation user identifier
    messages: list[ChatMessage]
    attachments: Optional[list[Attachment]] = None


class ResumeBody(BaseModel):
    conversationId: str
    value: str  # label of the option selected by the user


class FeedbackBody(BaseModel):
    feedbackId: str          # uuid generated by the frontend
    conversationId: str
    messageId: str           # assistant message that received the vote
    question: str            # last user question
    answer: str              # assistant answer text
    vote: str                # "up" | "down"


# ─── Padrões simples de factos pessoais (sem LLM extra) ──────────────────────
import re as _re

# Keywords that indicate crisis/distress — never extract facts from these messages.
_CRISIS_KEYWORDS = {
    "matar", "suicídio", "suicidio", "suicidar", "morrer", "não quero viver",
    "nao quero viver", "quero desaparecer", "acabar com tudo", "tirar a vida",
    "sem sentido", "não vale a pena", "nao vale a pena",
}

# Whitelist of recognised profession keywords to prevent false-positives like "pobre".
_JOB_WHITELIST = {
    "médico", "médica", "enfermeiro", "enfermeira", "professor", "professora",
    "engenheiro", "engenheira", "advogado", "advogada", "dentista", "arquiteto",
    "arquiteta", "economista", "gestor", "gestora", "programador", "programadora",
    "designer", "analista", "consultor", "consultora", "contabilista", "comerciante",
    "farmacêutico", "farmacêutica", "psicólogo", "psicóloga", "nutricionista",
    "fisioterapeuta", "veterinário", "veterinária", "jornalista", "juiz", "juíza",
}

_FACT_PATTERNS: list[tuple[str, str, _re.Pattern]] = [
    # name — only explicit self-identification patterns
    ("name", "nome",
     _re.compile(
         r"(?:meu nome é|chamo-me|sou o|sou a)\s+([A-ZÀ-Ü][a-zà-ü]+(?:\s+[A-ZÀ-Ü][a-zà-ü]+)*)",
         _re.IGNORECASE,
     )),
    # city — only explicit residence patterns
    ("city", "cidade",
     _re.compile(
         r"(?:moro em|vivo em|resido em)\s+([A-ZÀ-Ü][a-zà-ü]+(?:\s+[A-ZÀ-Ü][a-zà-ü]+)*)",
         _re.IGNORECASE,
     )),
    # monthly_income — capture numeric value in euros/month
    ("monthly_income", "rendimento mensal",
     _re.compile(
         r"(?:ganho|recebo|salário de|auferir?)\s+([\d\s.,]+)\s*(?:euros?|€)\s*(?:por\s+m[eê]s|\/m[eê]s|mensais?)?",
         _re.IGNORECASE,
     )),
    # job — only match against known profession whitelist (prevents "pobre", "doente", etc.)
    ("job", "profissão",
     _re.compile(
         r"(?:sou|trabalho como)\s+(?:um |uma )?(" + "|".join(_JOB_WHITELIST) + r")\b",
         _re.IGNORECASE,
     )),
]


def _is_crisis_message(text: str) -> bool:
    """Return True if the message contains crisis/distress language."""
    lower = text.lower()
    return any(kw in lower for kw in _CRISIS_KEYWORDS)


def _auto_extract_facts(user_id: str, text: str, mem) -> None:
    """Extract personal facts from user message using regex patterns and save them.

    Safety rules:
    - Never extract facts from crisis/distress messages.
    - Job extraction only matches whitelisted professions.
    - Income value is normalised (spaces/commas stripped).
    """
    if _is_crisis_message(text):
        print(f"[memory] skipping extraction — crisis message detected for user {user_id[:8]}")
        return

    for key, _desc, pattern in _FACT_PATTERNS:
        m = pattern.search(text)
        if m:
            value = m.group(1).strip().replace(" ", "").replace(",", ".")
            # For non-numeric facts, restore spaces (only strip for income)
            if key != "monthly_income":
                value = m.group(1).strip()
            if value and 1 <= len(value) <= 60:
                mem.save_fact(user_id, key, value)
                print(f"[memory] auto-saved: {key}={value!r} for user {user_id[:8]}")


def _get_graph():
    g = runtime.get("graph")
    if g is None:
        raise HTTPException(status_code=503, detail="Graph ainda nao esta pronto.")
    return g


def _build_user_message(body: ChatBody) -> HumanMessage:
    """
    Monta o HumanMessage a partir do payload.
    Se userId presente, injeta os factos do perfil do utilizador como contexto
    para que o direct_node e os agentes tenham acesso à memória de longo prazo.
    """
    last_text = body.messages[-1].content if body.messages else ""
    if body.attachments:
        names = ", ".join(a.name for a in body.attachments)
        suffix = f"\n\n[Anexos enviados pelo usuario: {names}]"
        last_text = (last_text + suffix) if last_text else suffix.strip()

    # Inject long-term user memory as a prefix if we have a userId
    if body.userId:
        try:
            from memory import get_memory
            mem = get_memory()
            # Auto-extract personal facts from the user's message (fire-and-forget)
            _auto_extract_facts(body.userId, last_text, mem)
            # Inject known facts as context prefix
            ctx = mem.as_context(body.userId)
            if ctx:
                last_text = f"{ctx}\n\n{last_text}"
        except Exception as e:
            print(f"[memory] failed to load user context: {e}")

    return HumanMessage(content=last_text, additional_kwargs={"user_id": body.userId or ""})


def _config_for(body: ChatBody) -> dict:
    cfg: dict = {
        "configurable": {"thread_id": body.conversationId},
        "recursion_limit": config.recursion_limit,
    }
    # Metadados visíveis no LangSmith UI por cada run
    if config.langsmith.enabled and config.langsmith.api_key:
        cfg["run_name"] = f"turn/{body.conversationId[:8]}"
        cfg["tags"]     = ["agentrix", config.web.domain]
        cfg["metadata"] = {
            "conversation_id": body.conversationId,
            "domain":          config.web.domain,
        }
    return cfg



def _sse(data: dict) -> bytes:
    """Encode a dict as a Server-Sent Event data line (AG-UI format)."""
    return f"data: {json.dumps(data, ensure_ascii=False)}\n\n".encode("utf-8")


@app.get("/health")
async def health():
    return {
        "ok": True,
        "graph_ready": "graph" in runtime,
        "model": config.ollama.model,
    }


@app.post("/chat")
async def chat(body: ChatBody):
    graph = _get_graph()
    reset_steps()
    try:
        result = await graph.ainvoke(
            {"messages": [_build_user_message(body)]},
            config=_config_for(body),
        )
        last = result["messages"][-1]

        content = last.content
        if isinstance(content, list):
            content = "".join(
                b.get("text", "") if isinstance(b, dict) else str(b)
                for b in content
            )
        # If the graph paused at a clarify interrupt, the last message is still
        # the user HumanMessage (no AI reply yet). Detect and surface the question.
        from langchain_core.messages import HumanMessage as _HumanMessage
        if isinstance(last, _HumanMessage):
            state = await graph.aget_state(_config_for(body))
            interrupts = [
                intr.value
                for task in (state.tasks or [])
                for intr in (getattr(task, "interrupts", None) or [])
            ]
            if interrupts:
                intr = interrupts[0]
                opts = ", ".join(o["label"] for o in (intr.get("options") or []))
                content = f"{intr.get('question', 'Por favor, seja mais específico.')} ({opts})"
            else:
                content = ""
        return {"reply": content}
    finally:
        print(turn_summary())


def _streaming_response(generator: AsyncIterator[bytes]) -> StreamingResponse:
    """Wrap an async bytes generator into a StreamingResponse with SSE headers."""
    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )

_suggest_llm = None


def _get_suggest_llm():
    """Lazy singleton LLM used only for follow-up suggestions."""
    global _suggest_llm
    if _suggest_llm is None:
        from langchain_google_genai import ChatGoogleGenerativeAI
        _suggest_llm = ChatGoogleGenerativeAI(
            model=config.gemini.model,
            google_api_key=config.gemini.api_key,
            temperature=config.gemini.temperature,
        )
    return _suggest_llm


async def _suggest_followups(question: str, answer: str) -> list[str]:
    """Gera 3 perguntas de seguimento curtas com sanitização rigorosa."""
    if not answer.strip():
        return []

    prompt = (
        "Com base na pergunta e resposta abaixo, sugere 3 perguntas de seguimento "
        "curtas (máx. 5 palavras cada). Responde APENAS com as 3, uma por linha, "
        "sem numeração, sem aspas, sem marcadores.\n\n"
        f"Pergunta: {question}\nResposta: {answer[:1500]}"
    )

    try:
        llm = _get_suggest_llm()
        resp = await llm.ainvoke(prompt)

        # Normaliza o conteúdo para string
        content = resp.content
        if isinstance(content, list):
            content = " ".join([str(b.get("text", "")) for b in content if isinstance(b, dict)])

        lines = []
        for line in content.splitlines():
            clean_line = re.sub(r'^\d+[\.\)]\s*', '', line).strip(" -•*\"'")
            if clean_line:
                lines.append(clean_line)

        return lines[:3]

    except Exception as e:
        print(f"[suggest] Erro na geração: {e}")
        return []



async def _run_graph_stream(
    graph,
    graph_input,
    run_config: dict,
    conversation_id: str,
    request: Optional[Request] = None,
    question: str = "",
):
    """Shared SSE generator for both /chat/stream and /chat/resume.

    Streams AG-UI events from a LangGraph run. After the astream loop ends,
    checks the graph state for a pending interrupt and emits an INTERRUPT event
    so the frontend can render interactive option cards.
    """
    run_id = str(uuid.uuid4())
    current_msg_id: str | None = None
    current_agent: str | None = None
    answer_buf: list[str] = []   # accumulates assistant text for follow-up suggestions

    tool_q: asyncio.Queue = asyncio.Queue()
    ctx_token = _tool_event_queue.set(tool_q)

    def _drain_tool_queue():
        events = []
        while not tool_q.empty():
            events.append(tool_q.get_nowait())
        return events

    yield _sse({"type": "RUN_STARTED", "runId": run_id, "threadId": conversation_id})

    try:
        async for chunk, metadata in graph.astream(
            graph_input,
            config=run_config,
            stream_mode="messages",
        ):
            if request and await request.is_disconnected():
                break

            node = (metadata or {}).get("langgraph_node")
            if node in ("supervisor", "clarify"):
                continue

            # Emit which agent is now active so the client can show an indicator
            # (and render a distinct crisis card when node == "crisis").

            if node and node != current_agent:
                if current_agent:
                    # AG-UI spec: close the previous lifecycle step before opening a new one.
                    yield _sse({"type": "STEP_FINISHED", "stepName": current_agent})
                current_agent = node
                # AG-UI spec: a lifecycle step -> STEP_STARTED with stepName.
                yield _sse({"type": "STEP_STARTED", "stepName": node})

            # Always flush tool events before any text check so rag_search
            # badges (from faq_agent) appear even when we suppress the text.
            for ev in _drain_tool_queue():
                yield _sse(ev)

            raw = getattr(chunk, "content", "") or ""
            if not isinstance(raw, str):
                try:
                    delta = "".join(
                        p.get("text", "")
                        for p in raw
                        if isinstance(p, dict) and p.get("type") != "thinking"
                    )
                except Exception:
                    delta = ""
            else:
                delta = raw

            if delta.startswith("FAQ_MISS"):
                continue

            if delta:
                if current_msg_id is None:
                    current_msg_id = str(uuid.uuid4())
                    yield _sse({
                        "type": "TEXT_MESSAGE_START",
                        "messageId": current_msg_id,
                        "role": "assistant",
                    })
                answer_buf.append(delta)
                yield _sse({
                    # AG-UI spec: streaming text chunk is TEXT_MESSAGE_CONTENT.
                    "type": "TEXT_MESSAGE_CONTENT",
                    "messageId": current_msg_id,
                    "delta": delta,
                })

        for ev in _drain_tool_queue():
            yield _sse(ev)

        if current_msg_id:
            yield _sse({"type": "TEXT_MESSAGE_END", "messageId": current_msg_id})

        if current_agent:
            # AG-UI spec: close the last lifecycle step once the run's graph loop ends.
            yield _sse({"type": "STEP_FINISHED", "stepName": current_agent})

        # ── Check for pending interrupt (e.g. clarify node paused the graph) ──
        try:
            state = await graph.aget_state(run_config)
            all_interrupts = [
                intr.value
                for task in (state.tasks or [])
                for intr in (getattr(task, "interrupts", None) or [])
            ]
            if all_interrupts:
                intr_val = all_interrupts[0]
                print(f"[server] interrupt detected: {intr_val}")
                # AG-UI spec: app-specific events go through CUSTOM (name + value).
                yield _sse({"type": "CUSTOM", "name": "interrupt", "value": intr_val})
        except Exception as exc:  # noqa: BLE001
            print(f"[server] aget_state error: {exc}")
            all_interrupts = []

        # ── Contextual follow-up suggestions (only on a real answer) ──────────
        if not all_interrupts and answer_buf:
            items = await _suggest_followups(question, "".join(answer_buf))
            if items:
                yield _sse({"type": "CUSTOM", "name": "suggestions", "value": {"items": items}})

        yield _sse({"type": "RUN_FINISHED", "runId": run_id, "threadId": conversation_id})

    except asyncio.CancelledError:
        raise
    except Exception as exc:  # noqa: BLE001
        for ev in _drain_tool_queue():
            yield _sse(ev)
        if current_msg_id:
            yield _sse({"type": "TEXT_MESSAGE_END", "messageId": current_msg_id})
        if current_agent:
            yield _sse({"type": "STEP_FINISHED", "stepName": current_agent})
        yield _sse({"type": "RUN_ERROR", "runId": run_id, "message": str(exc)})
    finally:
        _tool_event_queue.reset(ctx_token)
        print(turn_summary())


@app.post("/chat/stream")
async def chat_stream(body: ChatBody, request: Request):
    graph = _get_graph()
    reset_steps()
    run_config = _config_for(body)
    user_msg = _build_user_message(body)
    question = body.messages[-1].content if body.messages else ""

    return _streaming_response(
        _run_graph_stream(graph, {"messages": [user_msg]}, run_config, body.conversationId, request, question)
    )


@app.post("/chat/resume")
async def chat_resume(body: ResumeBody, request: Request):
    """Resume a graph that was paused at an interrupt (e.g. clarify node).

    The frontend sends the value selected by the user; we pass it to the graph
    via Command(resume=value) so the clarify_node can receive it and continue.
    """
    from langgraph.types import Command

    graph = _get_graph()
    reset_steps()
    run_config = _config_for(body)

    return _streaming_response(
        _run_graph_stream(graph, Command(resume=body.value), run_config, body.conversationId, request)
    )


@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    """
    Compat: o react-chat-ui usa /upload pra anexos genericos.
    Apenas le e retorna metadata. Nao indexa.
    """
    size = 0
    while chunk := await file.read(1024 * 64):
        size += len(chunk)
    return {
        "id": file.filename or "upload",
        "filename": file.filename,
        "content_type": file.content_type,
        "size": size,
        "note": "Use /documents/upload para indexar no RAG.",
    }


@app.post("/documents/upload")
async def documents_upload(file: UploadFile = File(...)):
    """
    Upload de documentos que devem ENTRAR no RAG (uploads persistentes).

    Aceita: .pdf, .docx, .txt, .md (texto extraido e indexado);
            imagens sao salvas mas nao indexadas (qwen2.5 nao e multimodal).

    Retorna: { id, filename, kind, chunks, size, note? }
    """
    import uuid as _uuid
    from pathlib import Path

    from extract import extract
    from rag import get_rag

    data = await file.read()
    size = len(data)

    # 1) Salva o original em uploads/ (mesmo que nao seja indexado)
    uploads_dir = Path(__file__).parent / "uploads"
    uploads_dir.mkdir(exist_ok=True)
    doc_id = _uuid.uuid4().hex
    safe_name = (file.filename or doc_id).replace("/", "_").replace("\\", "_")
    saved_path = uploads_dir / f"{doc_id}__{safe_name}"
    saved_path.write_bytes(data)

    # 2) Extrai texto conforme tipo
    extracted = extract(data, file.filename or "", file.content_type)

    # 3) Indexa no RAG se houver texto
    chunks = 0
    note = extracted.note
    if extracted.text.strip():
        try:
            rag = get_rag()
            chunks = rag.index_text(
                extracted.text,
                source=f"upload://{safe_name}",
                kind="upload",
                extra_metadata={
                    "doc_id": doc_id,
                    "filename": safe_name,
                    "content_type": file.content_type or "",
                },
            )
        except Exception as e:
            note = f"Texto extraido mas indexacao falhou: {e}"

    return {
        "id": doc_id,
        "filename": file.filename,
        "saved_as": str(saved_path.name),
        "kind": extracted.kind,
        "content_type": file.content_type,
        "size": size,
        "chunks": chunks,
        "note": note,
    }


@app.get("/documents")
async def list_documents():
    """Lista as fontes ja indexadas no RAG (debug)."""
    from rag import get_rag

    try:
        rag = get_rag()
        return {"count": rag.count(), "sources": rag.sources()}
    except Exception as e:  # noqa: BLE001
        raise HTTPException(500, f"Erro lendo RAG: {e}")


@app.get("/documents/stats")
async def rag_stats():
    """Diagnostico: contagem por kind, entidades, mentions. Use pra entender
    o estado do RAG sem precisar passar por agent."""
    from rag import get_rag

    try:
        rag = get_rag()
        return rag.stats()
    except Exception as e:  # noqa: BLE001
        raise HTTPException(500, f"Erro lendo stats: {e}")


@app.delete("/documents/{kind}")
async def delete_documents_by_kind(kind: str):
    """Apaga TODOS os chunks de um kind. Use com cuidado.

    Caso de uso: `DELETE /documents/search_results` pra limpar snippets
    de DDG antigos que estavam confundindo o RAG-first.
    """
    from rag import get_rag

    try:
        rag = get_rag()
        removed = rag.delete_by_kind(kind)
        return {"kind": kind, "removed": removed}
    except Exception as e:  # noqa: BLE001
        raise HTTPException(500, f"Erro removendo kind={kind}: {e}")


@app.get("/memory/{user_id}")
async def get_memory_facts(user_id: str):
    """Retorna todos os factos conhecidos de um utilizador."""
    from memory import get_memory
    try:
        return {"user_id": user_id, "facts": get_memory().load_facts(user_id)}
    except Exception as e:
        raise HTTPException(500, str(e))


@app.post("/memory/{user_id}")
async def save_memory_fact(user_id: str, body: dict):
    """Guarda ou actualiza um facto do utilizador. Body: {key, value}"""
    from memory import get_memory
    key = body.get("key", "").strip()
    value = body.get("value", "").strip()
    if not key or not value:
        raise HTTPException(422, "key and value required")
    try:
        get_memory().save_fact(user_id, key, value)
        return {"ok": True, "user_id": user_id, "key": key, "value": value}
    except Exception as e:
        raise HTTPException(500, str(e))


@app.delete("/memory/{user_id}/{key}")
async def delete_memory_fact(user_id: str, key: str):
    """Remove um facto do perfil do utilizador."""
    from memory import get_memory
    try:
        get_memory().delete_fact(user_id, key)
        return {"ok": True}
    except Exception as e:
        raise HTTPException(500, str(e))


@app.post("/feedback")
async def post_feedback(body: FeedbackBody):
    """Recebe um voto 👍/👎 do utilizador e persiste no grafo Neo4j.

    Usa rag_search(question, k=5) pra aproximar quais chunks foram usados
    na resposta (Option B: re-run da questão como proxy dos chunks servidos).
    Cria :Feedback node e incrementa feedback_positive / feedback_negative
    nos :Chunk nodes relevantes.
    """
    import uuid as _uuid

    from rag import get_rag

    if body.vote not in ("up", "down"):
        raise HTTPException(status_code=422, detail="vote must be 'up' or 'down'")

    try:
        rag = get_rag()

        # Aproxima os chunks usados re-rodando hybrid_search na questão
        hits = rag.hybrid_search(body.question, k=5)
        chunk_ids = [h.id for h in hits if h.id]

        rag.save_feedback(
            feedback_id=body.feedbackId or _uuid.uuid4().hex,
            conversation_id=body.conversationId,
            message_id=body.messageId,
            question=body.question,
            answer=body.answer,
            vote=body.vote,
            chunk_ids=chunk_ids,
        )

        return {
            "ok": True,
            "vote": body.vote,
            "chunks_updated": len(chunk_ids),
        }
    except Exception as e:  # noqa: BLE001
        raise HTTPException(500, f"Erro ao salvar feedback: {e}")


@app.get("/feedback/stats")
async def feedback_stats():
    """Diagnóstico: contagem de votos e top chunks por feedback."""
    from rag import get_rag

    try:
        rag = get_rag()
        return rag.feedback_stats()
    except Exception as e:  # noqa: BLE001
        raise HTTPException(500, f"Erro lendo feedback stats: {e}")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "server:app",
        host="0.0.0.0",
        port=config.port,
        reload=config.reload,
    )
